/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.tgiachi.diamond.homecontrol.server;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.scheduling.annotation.EnableScheduling;

@SpringBootApplication
@EnableAsync
@EnableScheduling
public class App implements CommandLineRunner {
    private static ConfigurableApplicationContext applicationContext;
    private static Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) throws Exception {
        logger.info("Initializing container");
        applicationContext = SpringApplication.run(App.class, args);
    }


    @Override
    public void run(String... args) throws Exception {

    }
}
